// Drives a constrained-random program (already generated by the test) into the
// DUT's instruction memory through the existing cpu_driver. Operand-setup must
// be disabled on the driver (cfg.enable_operand_setup = 0) so instructions are
// laid out contiguously at boot_pc + idx*4, matching the generator's PCs and
// the Spike golden image.
class cpu_rand_program_seq extends cpu_base_seq;
    `uvm_object_utils(cpu_rand_program_seq)

    // The test sets this before starting the sequence. If left null, the
    // sequence builds and randomizes its own program.
    cpu_rand_program program_;

    function new(string name = "cpu_rand_program_seq");
        super.new(name);
    endfunction

    task body();
        if (program_ == null) begin
            program_ = cpu_rand_program::type_id::create("program");
            if (!program_.randomize())
                `uvm_fatal(get_type_name(), "cpu_rand_program randomize failed")
            program_.generate_program();
        end

        `uvm_info(get_type_name(), $sformatf(
            "Driving %0d instructions (raw=%0d%% waw=%0d%% load_use=%0d%% branch_cluster=%0d%%)",
            program_.prog.size(), program_.raw_pct, program_.waw_pct,
            program_.load_use_pct, program_.branch_cluster_pct), UVM_LOW)

        foreach (program_.prog[i]) begin
            cpu_instr_item tr;
            tr = program_.prog[i];
            start_item(tr);
            finish_item(tr);
        end
    endtask

endclass
