class cpu_env extends uvm_env;
    `uvm_component_utils(cpu_env)

    cpu_cfg             cfg;
    cpu_agent           agt;
    cpu_scoreboard      sb;
    cpu_spike_scoreboard sb_spike;
    cpu_int_alu_ref_model   rm;
    cpu_coverage        cov_commit;
    cpu_instr_coverage  cov_instr;
    cpu_baremetal_commit_coverage cov_bm_commit;
    cpu_baremetal_dcache_coverage cov_bm_dcache;
    cpu_spike_trace_coverage      cov_spike_trace;

    function new(string name = "cpu_env", uvm_component parent = null);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);

        if (!uvm_config_db#(cpu_cfg)::get(this, "", "cfg", cfg)) begin
            cfg = cpu_cfg::type_id::create("cfg");
            `uvm_info(get_type_name(), "No cpu_cfg in config_db; using defaults", UVM_LOW)
        end
        uvm_config_db#(cpu_cfg)::set(this, "*", "cfg", cfg);

        agt = cpu_agent::type_id::create("agt", this);

        if (cfg.enable_scoreboard)
            sb = cpu_scoreboard::type_id::create("sb", this);

        if (cfg.enable_spike_scoreboard)
            sb_spike = cpu_spike_scoreboard::type_id::create("sb_spike", this);

        if (cfg.enable_ref_model)
            rm = cpu_int_alu_ref_model::type_id::create("rm", this);

        if (cfg.enable_coverage) begin
            cov_commit = cpu_coverage::type_id::create("cov_commit", this);
            cov_instr  = cpu_instr_coverage::type_id::create("cov_instr", this);
        end

        if (cfg.enable_baremetal_coverage) begin
            cov_bm_commit   = cpu_baremetal_commit_coverage::type_id::create("cov_bm_commit", this);
            cov_bm_dcache   = cpu_baremetal_dcache_coverage::type_id::create("cov_bm_dcache", this);
            cov_spike_trace = cpu_spike_trace_coverage::type_id::create("cov_spike_trace", this);
        end
    endfunction

    function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);

        if (cfg.enable_scoreboard) begin
            agt.mon.ap_commit.connect(sb.imp_commit);
            if (cfg.is_active == UVM_ACTIVE)
                agt.drv.ap_instr.connect(sb.imp_instr);
        end

        if (cfg.enable_spike_scoreboard)
            agt.mon.ap_commit.connect(sb_spike.imp_commit);

        if (cfg.enable_ref_model && cfg.is_active == UVM_ACTIVE)
            agt.drv.ap_instr.connect(rm.imp_instr);

        if (cfg.enable_coverage) begin
            agt.mon.ap_commit.connect(cov_commit.analysis_export);
            if (cfg.is_active == UVM_ACTIVE)
                agt.drv.ap_instr.connect(cov_instr.analysis_export);
        end

        if (cfg.enable_baremetal_coverage) begin
            agt.mon.ap_commit.connect(cov_bm_commit.analysis_export);
            agt.dmon.ap_dcache.connect(cov_bm_dcache.analysis_export);
        end
    endfunction

    virtual function void report_phase(uvm_phase phase);
        int    fd;
        real   commit_pct = 0.0;
        real   commit_m2_pct = 0.0;
        real   alu_m2_pct = 0.0;
        real   alu_stretch_pct = 0.0;
        real   setup_pct  = 0.0;
        real   goal;
        string status;
        string report_path = "coverage_summary.txt";

        super.report_phase(phase);
        if (!cfg.enable_coverage)
            return;

        void'($value$plusargs("COV_REPORT=%s", report_path));
        goal = cfg.coverage_goal_pct;

        if (cov_commit != null) begin
            commit_pct    = cov_commit.cg_commit.get_coverage();
            commit_m2_pct = cov_commit.cg_commit_m2.get_coverage();
        end
        if (cov_instr != null) begin
            alu_m2_pct      = cov_instr.cg_alu_m2.get_coverage();
            alu_stretch_pct = cov_instr.cg_alu_main.get_coverage();
            setup_pct       = cov_instr.cg_setup.get_coverage();
        end

        if (commit_m2_pct >= goal && alu_m2_pct >= goal && setup_pct >= goal)
            status = "CLOSED";
        else
            status = "OPEN";

        fd = $fopen(report_path, "w");
        if (fd != 0) begin
            $fdisplay(fd, "Tomasulo3CPU UVM functional coverage summary (Milestone 2 INT ALU)");
            $fdisplay(fd, "Generated by cpu_env @ %0t", $time);
            $fdisplay(fd, "Sign-off goal: %.0f%% on in-scope covergroups", goal);
            $fdisplay(fd, "Status: %0s", status);
            $fdisplay(fd, "");
            $fdisplay(fd, "Covergroup,Score,Goal,Result,Notes");
            $fdisplay(fd, "cg_commit_m2,%.2f,%.0f,%0s,GPR retire on ALU path",
                commit_m2_pct, goal, (commit_m2_pct >= goal) ? "PASS" : "OPEN");
            $fdisplay(fd, "cg_alu_m2,%.2f,%.0f,%0s,ADD/ADDW/SUB/SUBW opcode bins",
                alu_m2_pct, goal, (alu_m2_pct >= goal) ? "PASS" : "OPEN");
            $fdisplay(fd, "cg_setup,%.2f,%.0f,%0s,ADDI/LD operand setup",
                setup_pct, goal, (setup_pct >= goal) ? "PASS" : "OPEN");
            $fdisplay(fd, "cg_alu_main_stretch,%.2f,N/A,INFO,cross + result classes (ongoing)",
                alu_stretch_pct);
            $fdisplay(fd, "cg_commit_full,%.2f,N/A,INFO,Full CPU commit model (stores/CSR/traps deferred)",
                commit_pct);
            $fclose(fd);
        end

        `uvm_info(get_type_name(), $sformatf(
            "Coverage closure status=%0s report=%0s m2=%.1f%% alu_m2=%.1f%% setup=%.1f%%",
            status, report_path, commit_m2_pct, alu_m2_pct, setup_pct), UVM_LOW)
    endfunction

endclass
