`timescale 1ns/1ps

// Tomasulo CPU subsystem with the L1 data cache and its backing memory.
// The instruction-memory port remains external so a testbench or future
// I-cache can provide instructions independently.
module CPU_L1DCache #(
    parameter int unsigned INSTR_WIDTH             = 32,
    parameter int unsigned IMEM_DEPTH              = 64,
    parameter int unsigned IMEM_WIDTH              = 32,
    parameter int unsigned IMEM_DEPTH_WORD         = IMEM_DEPTH - 1,
    parameter int unsigned XLEN                    = 64,
    parameter int unsigned ARCH_REG_COUNT          = 32,
    parameter int unsigned ARCH_REG_WIDTH          = $clog2(ARCH_REG_COUNT),
    parameter int unsigned REG_FILE_DATA_WIDTH     = 64,
    parameter int unsigned PHY_REGISTER_FILE_WIDTH = 7,
    parameter int unsigned DMEM_WIDTH              = 64,
    parameter int unsigned DMEM_DEPTH              = 64,
    parameter int unsigned W_BYTE_NUM              = DMEM_WIDTH / 8,
    parameter int unsigned BPB_PC_BITS             = 3,
    parameter int unsigned NUM_WAYS                = 4,
    parameter int unsigned IFQ_DEPTH               = 16,
    parameter int unsigned RAS_DEPTH               = 4,
    parameter int unsigned FRL_SIZE                = 128,
    parameter int unsigned FRL_PTR_WIDTH           = $clog2(FRL_SIZE),
    parameter int unsigned NUM_CHECKPOINT          = 8,
    parameter int unsigned ROB_DEPTH               = 16,
    parameter int unsigned ROB_INDEX_WIDTH         = $clog2(ROB_DEPTH),
    parameter int unsigned SB_DEPTH                = 4,
    parameter int unsigned SB_INDEX_WIDTH          = $clog2(SB_DEPTH),
    parameter int unsigned ISSUE_QUEUE_DEPTH       = 8,
    parameter int unsigned LSB_DEPTH               = 4,
    parameter int unsigned DIV_CYCLES              = 64,
    parameter int unsigned MUL_CYCLES              = 4,
    parameter int unsigned INT_CYCLES              = 1,
    parameter int unsigned LD_ST_CYCLES            = 1,
    parameter int unsigned OPCODE_WIDTH            = 7,
    parameter int unsigned DCACHE_MEM_IDX_BITS     = 16
) (
    input  logic                            clk,
    input  logic                            rst_n,

    output logic [IMEM_DEPTH-1:0]           imem_addr,
    output logic                            imem_req_valid,
    input  logic [INSTR_WIDTH-1:0]          imem_resp_data,
    input  logic                            imem_resp_valid,
    output logic                            imem_resp_ready,

    input  logic                            dcache_mem_init_en,
    input  logic [DCACHE_MEM_IDX_BITS-1:0]  dcache_mem_init_idx,
    input  logic [DMEM_WIDTH-1:0]           dcache_mem_init_data,
    output logic [31:0]                     dcache_hits,
    output logic [31:0]                     dcache_misses,

    // Observation ports for verification and performance monitoring.
    output logic                            dcache_rready,
    output logic                            dcache_rresp_valid,
    output logic [REG_FILE_DATA_WIDTH-1:0]  dcache_rdata,
    output logic [DMEM_DEPTH-1:0]           dcache_raddr,
    output logic                            dcache_rvalid,
    output logic                            dcache_rresp_ready,
    output logic                            dcache_wready,
    output logic                            dcache_wresp_valid,
    output logic                            dcache_write,
    output logic [DMEM_WIDTH-1:0]           dcache_sw_data,
    output logic [W_BYTE_NUM-1:0]           dcache_wstrb,
    output logic [DMEM_DEPTH-1:0]           dcache_sw_addr,
    output logic                            dcache_wvalid,
    output logic                            dcache_wresp_ready
);

    CPU #(
        .INSTR_WIDTH             (INSTR_WIDTH),
        .IMEM_DEPTH              (IMEM_DEPTH),
        .IMEM_WIDTH              (IMEM_WIDTH),
        .IMEM_DEPTH_WORD         (IMEM_DEPTH_WORD),
        .XLEN                    (XLEN),
        .ARCH_REG_COUNT          (ARCH_REG_COUNT),
        .ARCH_REG_WIDTH          (ARCH_REG_WIDTH),
        .REG_FILE_DATA_WIDTH     (REG_FILE_DATA_WIDTH),
        .PHY_REGISTER_FILE_WIDTH (PHY_REGISTER_FILE_WIDTH),
        .DMEM_WIDTH              (DMEM_WIDTH),
        .DMEM_DEPTH              (DMEM_DEPTH),
        .W_BYTE_NUM              (W_BYTE_NUM),
        .BPB_PC_BITS             (BPB_PC_BITS),
        .NUM_WAYS                (NUM_WAYS),
        .IFQ_DEPTH               (IFQ_DEPTH),
        .RAS_DEPTH               (RAS_DEPTH),
        .FRL_SIZE                (FRL_SIZE),
        .FRL_PTR_WIDTH           (FRL_PTR_WIDTH),
        .NUM_CHECKPOINT          (NUM_CHECKPOINT),
        .ROB_DEPTH               (ROB_DEPTH),
        .ROB_INDEX_WIDTH         (ROB_INDEX_WIDTH),
        .SB_DEPTH                (SB_DEPTH),
        .SB_INDEX_WIDTH          (SB_INDEX_WIDTH),
        .ISSUE_QUEUE_DEPTH       (ISSUE_QUEUE_DEPTH),
        .LSB_DEPTH               (LSB_DEPTH),
        .DIV_CYCLES              (DIV_CYCLES),
        .MUL_CYCLES              (MUL_CYCLES),
        .INT_CYCLES              (INT_CYCLES),
        .LD_ST_CYCLES            (LD_ST_CYCLES),
        .OPCODE_WIDTH            (OPCODE_WIDTH)
    ) u_cpu (
        .clk                (clk),
        .rst_n              (rst_n),
        .imem_addr          (imem_addr),
        .imem_req_valid     (imem_req_valid),
        .imem_resp_data     (imem_resp_data),
        .imem_resp_valid    (imem_resp_valid),
        .imem_resp_ready    (imem_resp_ready),
        .dcache_rready      (dcache_rready),
        .dcache_rresp_valid (dcache_rresp_valid),
        .dcache_rdata       (dcache_rdata),
        .dcache_raddr       (dcache_raddr),
        .dcache_rvalid      (dcache_rvalid),
        .dcache_rresp_ready (dcache_rresp_ready),
        .dcache_wready      (dcache_wready),
        .dcache_wresp_valid (dcache_wresp_valid),
        .dcache_write       (dcache_write),
        .dcache_sw_data     (dcache_sw_data),
        .dcache_wstrb       (dcache_wstrb),
        .dcache_sw_addr     (dcache_sw_addr),
        .dcache_wvalid      (dcache_wvalid),
        .dcache_wresp_ready (dcache_wresp_ready)
    );

    dcache_tomasulo_wrap #(
        .CPU_ADDR_WIDTH (DMEM_DEPTH),
        .DATA_WIDTH     (DMEM_WIDTH),
        .STRB_WIDTH     (W_BYTE_NUM),
        .MEM_IDX_BITS   (DCACHE_MEM_IDX_BITS)
    ) u_dcache (
        .clk                (clk),
        .rst_n              (rst_n),
        .dcache_rvalid      (dcache_rvalid),
        .dcache_raddr       (dcache_raddr),
        .dcache_rresp_ready (dcache_rresp_ready),
        .dcache_rready      (dcache_rready),
        .dcache_rresp_valid (dcache_rresp_valid),
        .dcache_rdata       (dcache_rdata),
        .dcache_wvalid      (dcache_wvalid),
        .dcache_write       (dcache_write),
        .dcache_sw_addr     (dcache_sw_addr),
        .dcache_sw_data     (dcache_sw_data),
        .dcache_wstrb       (dcache_wstrb),
        .dcache_wresp_ready (dcache_wresp_ready),
        .dcache_wready      (dcache_wready),
        .dcache_wresp_valid (dcache_wresp_valid),
        .mem_init_en        (dcache_mem_init_en),
        .mem_init_idx       (dcache_mem_init_idx),
        .mem_init_data      (dcache_mem_init_data),
        .stat_hits          (dcache_hits),
        .stat_misses        (dcache_misses)
    );

endmodule
