#!/usr/bin/env python3
"""Generate objdump -d disassembly files next to each built test ELF."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BUILD = ROOT / "build"

FAILED_MANIFEST = ROOT / "results_latest.txt"


def find_objdump(bin_dir: Path | None) -> str:
    from riscv_toolchain import resolve_bin_dir, resolve_prefix, tool_path

    directory = resolve_bin_dir(bin_dir)
    prefix = resolve_prefix(directory)
    return tool_path(directory, prefix, "objdump")


def list_failed_from_results() -> list[str]:
    if not FAILED_MANIFEST.is_file():
        return []
    names: list[str] = []
    in_failed = False
    for line in FAILED_MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("## FAILED"):
            in_failed = True
            continue
        if in_failed and line.startswith("## "):
            break
        if in_failed and line.startswith("rv64"):
            names.append(line.split()[0])
    return names


def gen_dump(objdump: str, elf: Path, out: Path) -> None:
    result = subprocess.run(
        [objdump, "-d", "-M", "no-aliases", str(elf)],
        check=True,
        capture_output=True,
        text=True,
    )
    header = (
        f"# Disassembly of {elf.name}\n"
        f"# Generated by: {objdump} -d -M no-aliases\n\n"
    )
    out.write_text(header + result.stdout, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bin-dir",
        type=Path,
        default=None,
        help="RISC-V toolchain bin directory",
    )
    parser.add_argument(
        "--failed-only",
        action="store_true",
        help="Only dirs listed under FAILED in results_latest.txt",
    )
    parser.add_argument(
        "tests",
        nargs="*",
        help="Build dir names (e.g. rv64ui-lui). Default: all dirs under build/",
    )
    args = parser.parse_args()

    objdump = find_objdump(args.bin_dir)

    if args.tests:
        dirs = [BUILD / t for t in args.tests]
    elif args.failed_only:
        dirs = [BUILD / t for t in list_failed_from_results()]
    else:
        dirs = sorted(p for p in BUILD.iterdir() if p.is_dir())

    count = 0
    for d in dirs:
        if not d.is_dir():
            print(f"skip (no dir): {d.name}", file=sys.stderr)
            continue
        elfs = list(d.glob("*.elf"))
        if not elfs:
            print(f"skip (no elf): {d.name}", file=sys.stderr)
            continue
        elf = elfs[0]
        out = d / f"{elf.stem}.dump"
        gen_dump(objdump, elf, out)
        print(f"wrote {out}")
        count += 1

    print(f"\n{count} dump file(s) under {BUILD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
